# Generated by Django 4.2.6 on 2023-10-30 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='概要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('like_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='topics_account', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('tags', models.ManyToManyField(to='topics.tag', verbose_name='タグ')),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('commented_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='topics.topic', verbose_name='トピック')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_account', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
