# Generated by Django 4.2.5 on 2023-10-07 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='概要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('like_count', models.IntegerField(default=0)),
                ('creted_by_id', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='topics_account', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('tags', models.ManyToManyField(blank=True, to='topics.tags', verbose_name='タグ')),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_account', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='topics.topics', verbose_name='トピック')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
