# Generated by Django 4.2.5 on 2023-10-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_rename_commentd_to_comments_commented_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='creted_by',
            new_name='created_by',
        ),
    ]
