# Generated by Django 4.2.5 on 2023-10-15 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_rename_creted_by_topics_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commented_by',
            new_name='created_by',
        ),
    ]
