# Generated by Django 4.2.5 on 2023-09-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='region',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
